/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as CotacoesIndexRouteImport } from './routes/cotacoes.index'
import { Route as CotacoesIdRouteImport } from './routes/cotacoes.$id'
import { Route as FornecedorPropostaRouteImport } from './routes/fornecedor.proposta'
import { Route as ObrasIndexRouteImport } from './routes/obras.index'
import { Route as ObrasIdRouteImport } from './routes/obras.$id'
import { Route as OrcamentosIndexRouteImport } from './routes/orcamentos.index'
import { Route as OrcamentosObraIdOrcamentoIdRouteImport } from './routes/orcamentos.$obraId.$orcamentoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesIndexRoute = CotacoesIndexRouteImport.update({
  id: '/cotacoes/',
  path: '/cotacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesIdRoute = CotacoesIdRouteImport.update({
  id: '/cotacoes/$id',
  path: '/cotacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorPropostaRoute = FornecedorPropostaRouteImport.update({
  id: '/fornecedor/proposta',
  path: '/fornecedor/proposta',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIndexRoute = ObrasIndexRouteImport.update({
  id: '/obras/',
  path: '/obras/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIdRoute = ObrasIdRouteImport.update({
  id: '/obras/$id',
  path: '/obras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosIndexRoute = OrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosObraIdOrcamentoIdRoute =
  OrcamentosObraIdOrcamentoIdRouteImport.update({
    id: '/orcamentos/$obraId/$orcamentoId',
    path: '/orcamentos/$obraId/$orcamentoId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/cotacoes/$id': typeof CotacoesIdRoute
  '/fornecedor/proposta': typeof FornecedorPropostaRoute
  '/obras/$id': typeof ObrasIdRoute
  '/cotacoes/': typeof CotacoesIndexRoute
  '/obras/': typeof ObrasIndexRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
  '/orcamentos/$obraId/$orcamentoId': typeof OrcamentosObraIdOrcamentoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/cotacoes/$id': typeof CotacoesIdRoute
  '/fornecedor/proposta': typeof FornecedorPropostaRoute
  '/obras/$id': typeof ObrasIdRoute
  '/cotacoes': typeof CotacoesIndexRoute
  '/obras': typeof ObrasIndexRoute
  '/orcamentos': typeof OrcamentosIndexRoute
  '/orcamentos/$obraId/$orcamentoId': typeof OrcamentosObraIdOrcamentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/cotacoes/$id': typeof CotacoesIdRoute
  '/fornecedor/proposta': typeof FornecedorPropostaRoute
  '/obras/$id': typeof ObrasIdRoute
  '/cotacoes/': typeof CotacoesIndexRoute
  '/obras/': typeof ObrasIndexRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
  '/orcamentos/$obraId/$orcamentoId': typeof OrcamentosObraIdOrcamentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diario'
    | '/cotacoes/$id'
    | '/fornecedor/proposta'
    | '/obras/$id'
    | '/cotacoes/'
    | '/obras/'
    | '/orcamentos/'
    | '/orcamentos/$obraId/$orcamentoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diario'
    | '/cotacoes/$id'
    | '/fornecedor/proposta'
    | '/obras/$id'
    | '/cotacoes'
    | '/obras'
    | '/orcamentos'
    | '/orcamentos/$obraId/$orcamentoId'
  id:
    | '__root__'
    | '/'
    | '/diario'
    | '/cotacoes/$id'
    | '/fornecedor/proposta'
    | '/obras/$id'
    | '/cotacoes/'
    | '/obras/'
    | '/orcamentos/'
    | '/orcamentos/$obraId/$orcamentoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiarioRoute: typeof DiarioRoute
  CotacoesIdRoute: typeof CotacoesIdRoute
  FornecedorPropostaRoute: typeof FornecedorPropostaRoute
  ObrasIdRoute: typeof ObrasIdRoute
  CotacoesIndexRoute: typeof CotacoesIndexRoute
  ObrasIndexRoute: typeof ObrasIndexRoute
  OrcamentosIndexRoute: typeof OrcamentosIndexRoute
  OrcamentosObraIdOrcamentoIdRoute: typeof OrcamentosObraIdOrcamentoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes/': {
      id: '/cotacoes/'
      path: '/cotacoes'
      fullPath: '/cotacoes/'
      preLoaderRoute: typeof CotacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes/$id': {
      id: '/cotacoes/$id'
      path: '/cotacoes/$id'
      fullPath: '/cotacoes/$id'
      preLoaderRoute: typeof CotacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/proposta': {
      id: '/fornecedor/proposta'
      path: '/fornecedor/proposta'
      fullPath: '/fornecedor/proposta'
      preLoaderRoute: typeof FornecedorPropostaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/': {
      id: '/obras/'
      path: '/obras'
      fullPath: '/obras/'
      preLoaderRoute: typeof ObrasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/$id': {
      id: '/obras/$id'
      path: '/obras/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof ObrasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/': {
      id: '/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof OrcamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/$obraId/$orcamentoId': {
      id: '/orcamentos/$obraId/$orcamentoId'
      path: '/orcamentos/$obraId/$orcamentoId'
      fullPath: '/orcamentos/$obraId/$orcamentoId'
      preLoaderRoute: typeof OrcamentosObraIdOrcamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiarioRoute: DiarioRoute,
  CotacoesIdRoute: CotacoesIdRoute,
  FornecedorPropostaRoute: FornecedorPropostaRoute,
  ObrasIdRoute: ObrasIdRoute,
  CotacoesIndexRoute: CotacoesIndexRoute,
  ObrasIndexRoute: ObrasIndexRoute,
  OrcamentosIndexRoute: OrcamentosIndexRoute,
  OrcamentosObraIdOrcamentoIdRoute: OrcamentosObraIdOrcamentoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
